image: registry.green-rabbit.net:5000/kimata/local_ubuntu:240730E

stages:
    - build-image
    - renovate

build-image:
    stage: build-image

    variables:
        BUILDER: arm_builder

    script:
        - cp /etc/gitlab-runner/certs/local-ca.crt /usr/local/share/ca-certificates/w
        - ls -la /usr/local/share/ca-certificates/local-ca.crt
        - cat /usr/local/share/ca-certificates/
        - update-ca-certificates

        - export GIT_SSL_NO_VERIFY=1
        - git clone https://gitlab.green-rabbit.net/kimata/sense-config.git
        - mv sense-config/*.yaml ./
        - git config --global --add safe.directory ${PWD}

        - docker buildx create --name ${BUILDER} --use
        - docker buildx use ${BUILDER}
        - docker buildx build --platform linux/amd64,linux/arm64/v8 --cache-from type=registry,ref=${CI_REGISTRY_IMAGE}:cache --cache-to type=registry,ref=${CI_REGISTRY_IMAGE}:cache --build-arg IMAGE_BUILD_DATE=$(date --iso-8601=seconds) --push --tag ${CI_REGISTRY_IMAGE} .


renovate:
    stage: renovate
    image:
        name: registry.green-rabbit.net:5000/kimata/local_renovate:38

        entrypoint: [""]
    script:
        - renovate --platform gitlab --token ${RENOVATE_TOKEN} --endpoint ${CI_SERVER_URL}/api/v4 ${CI_PROJECT_PATH}
    rules:
        - if: '$CI_COMMIT_BRANCH != "master"'
          when: never
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - changes:
            - renovate.json
