image: registry.green-rabbit.net:5000/kimata/local_ubuntu:241105B

stages:
    - build-image
    - deploy
    - renovate

build-image:
    stage: build-image

    variables:
        BUILDER: arm_builder

    script:
        - export GIT_SSL_NO_VERIFY=1
        - git clone https://gitlab.green-rabbit.net/kimata/sense-config.git
        - mv sense-config/*.yaml ./
        - git config --global --add safe.directory ${PWD}

        - docker buildx create --name ${BUILDER} --use --config /etc/buildkitd.toml
        - docker buildx use ${BUILDER}
        - docker buildx build --platform linux/amd64,linux/arm64/v8 --cache-from type=registry,ref=${CI_REGISTRY_IMAGE}:cache --cache-to type=registry,ref=${CI_REGISTRY_IMAGE}:cache --build-arg IMAGE_BUILD_DATE=$(date --iso-8601=seconds) --push --tag ${CI_REGISTRY_IMAGE} .

# deploy:
#     stage: deploy

#     dependencies: []

#     image:
#         name: bitnami/kubectl:latest
#         entrypoint: ['']

#     script:
#         - kubectl config get-contexts
#         - kubectl config use-context kimata/sensing-py:pod-rollout
#         - kubectl --insecure-skip-tls-verify=true rollout restart -n sensor daemonset sensor-weather-deployment
#         - kubectl --insecure-skip-tls-verify=true rollout restart -n sensor daemonset sensor-room-deployment
#         - kubectl --insecure-skip-tls-verify=true rollout restart -n sensor daemonset sensor-aqua-deployment

#     rules:
#         # NOTE: 自動実行ではデプロイしない
#         - if: $CI_PIPELINE_SOURCE == "schedule"
#           when: never
#         - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
#           when: never
#         - when: on_success

renovate:
    stage: renovate
    image:
        name: registry.green-rabbit.net:5000/kimata/local_renovate:38

        entrypoint: [""]
    script:
        - renovate --platform gitlab --token ${RENOVATE_TOKEN} --endpoint ${CI_SERVER_URL}/api/v4 ${CI_PROJECT_PATH}
    rules:
        - if: '$CI_COMMIT_BRANCH != "master"'
          when: never
        - if: '$CI_PIPELINE_SOURCE == "schedule"'
        - changes:
            - renovate.json
